FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    git \
    python-is-python3 \
    g++ \
    libxml2-dev \
    python3-dev \
    net-tools 


WORKDIR /app

RUN git clone https://github.com/USNavalResearchLaboratory/protolib.git

WORKDIR /app/protolib

RUN ./waf configure
RUN ./waf list
RUN ./waf --prefix=/app/ --debug --build-python --targets=protoCapExample
RUN ./waf install